Import the libraries

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

Read the given data into Python

In [2]:
data = pd.read_csv("/content/sample_data_set_2 - Sheet1 (1).csv")
data = data.dropna()
data = data.reset_index(drop=True)
print(data)

In [4]:
# Drop some columns
data_new = data.drop(['Fill Rate','Render Rate','State'], axis = 1)

# Group the dataset
data2 = data_new.groupby(['Date','App','Ad Requests'],as_index=False).sum(['Revenue','Ad Responses','Impressions','1st Clicks','2nd Clicks'])

In [7]:
# Now group by 'App'
data2 = data2.groupby(['App'],as_index=False).sum()

In [8]:
data2.head()

                      App  Ad Requests  ...  1st Clicks  2nd Clicks
0  (SDK X) Cricket Mazza      51726667  ...      170817       36893
1                12611047            0  ...           0           0
2                39052237            0  ...           0           0
3            4 Digit Code        43622  ...        4366        1510
4                86507421            4  ...           0           0

[5 rows x 7 columns]

In [9]:
#Enter the fill rates and Render rates
data2['Fill Rate'] = (data2['Ad Responses']/data2['Ad Requests'])*100
data2['Render Rate']= (data2['Impressions']/data2['Ad Responses'])*100

data2 = data2.dropna()

Correlation Matrix without Ad Groups

In [12]:
data2.corr()

              Ad Requests   Revenue  ...  Fill Rate  Render Rate
Ad Requests      1.000000  0.705207  ...  -0.031519     0.169754
Revenue          0.705207  1.000000  ...   0.042412     0.193435
Ad Responses     0.999977  0.706308  ...  -0.028747     0.169512
Impressions      0.999187  0.682942  ...  -0.029879     0.172408
1st Clicks       0.559042  0.741669  ...  -0.047454     0.219090
2nd Clicks       0.768429  0.892331  ...  -0.053321     0.195814
Fill Rate       -0.031519  0.042412  ...   1.000000    -0.206661
Render Rate      0.169754  0.193435  ...  -0.206661     1.000000

[8 rows x 8 columns]

K-Means Clustering Classification- without Ad Groups

In [ ]:
x = data2[['Revenue']]


#Find Number of clusters
wcss=[]
for i in range(1,7):
  kmeans = KMeans(i)
  kmeans.fit(x)
  wcss_iter = kmeans.inertia_
  wcss.append(wcss_iter)

number_clusters = range(1,7)
plt.plot(number_clusters,wcss)
plt.title('The Elbow title')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
#2


kmeans = KMeans(2)
kmeans.fit(x)


identified_clusters = kmeans.fit_predict(x)
identified_clusters



data_with_clusters = data2.copy()
data_with_clusters['Clusters'] = identified_clusters

In [ ]:
#Sort the new data with clusters
data_with_clusters.sort_values(by='Clusters', ascending = False)

In [ ]:
###################################################

Dataset with Ad Groups

In [97]:
data_groups = data_new.groupby(['Ad Group'],as_index=False).sum()
data_groups['Fill Rate'] = (data_groups['Ad Responses']/data_groups['Ad Requests'])*100
data_groups['Render Rate']= (data_groups['Impressions']/data_groups['Ad Responses'])*100
data_groups = data_groups.dropna()

K-Means Clusterinig Classification with Ad Groups

In [ ]:
y = data_groups[['Render Rate']]

kmeans_g = KMeans(2)
kmeans_g.fit(y)

identified_clusters_g = kmeans_g.fit_predict(y)
identified_clusters_g

data_with_clusters_g = data_groups.copy()
data_with_clusters_g['Clusters'] = identified_clusters_g

data_with_clusters_g.sort_values(by='Clusters', ascending = True)

In [157]:
# Cluster 0
(data_with_clusters_g['Clusters']==0).sum(axis=0)

113

Correlation Matrix with Ad Groups

In [43]:
data_groups.corr()

              Ad Requests   Revenue  ...  Fill Rate  Render Rate
Ad Requests      1.000000  0.361314  ...  -0.159400     0.151581
Revenue          0.361314  1.000000  ...   0.019853     0.042894
Ad Responses     0.450826  0.350134  ...   0.043055     0.060424
Impressions      0.433520  0.319465  ...   0.044387     0.064381
1st Clicks       0.295128  0.430597  ...   0.012340     0.100708
2nd Clicks       0.407914  0.496317  ...  -0.023507     0.101172
Fill Rate       -0.159400  0.019853  ...   1.000000    -0.365430
Render Rate      0.151581  0.042894  ...  -0.365430     1.000000

[8 rows x 8 columns]